# Generated by Django 5.1.5 on 2025-02-03 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Donation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('donor_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone_number', models.CharField(max_length=15)),
                ('collection_address', models.TextField()),
                ('food_category', models.CharField(choices=[('veg', 'Vegetarian'), ('non_veg', 'Non-Vegetarian'), ('both', 'Both')], max_length=10)),
                ('quantity', models.PositiveIntegerField()),
                ('food_preparation_date', models.DateField()),
                ('special_note', models.TextField(blank=True, null=True)),
                ('accept_terms', models.BooleanField(default=False)),
            ],
        ),
    ]
