# Generated by Django 5.1.5 on 2025-02-12 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodTest', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('message', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
