# Generated by Django 5.1.5 on 2025-02-15 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodTest', '0002_contact'),
    ]

    operations = [
        migrations.CreateModel(
            name='DonorProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('donor_name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('total_donated', models.PositiveIntegerField(default=0)),
                ('reward_level', models.CharField(default='New', max_length=20)),
            ],
        ),
    ]
