# Generated by Django 5.1.5 on 2025-07-09 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodTest', '0004_blog'),
    ]

    operations = [
        migrations.CreateModel(
            name='Inventory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('quantity', models.IntegerField()),
                ('expiry_date', models.DateField()),
            ],
        ),
    ]
